# Generated by Django 6.0.3 on 2026-04-04 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='orders.order'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='orders.order'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['payment_method', 'created_at'], name='finance_bil_payment_3f1083_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['location', 'created_at'], name='finance_tra_locatio_6f2b54_idx'),
        ),
    ]
