# Generated by Django 5.2.13 on 2026-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('inventory', '0002_product_product_price_gt_zero_and_more'),
        ('orders', '0003_order_order_total_amount_gte_zero_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__gt', 0)), name='bill_amount_paid_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'),
        ),
    ]
