# Generated by Django 5.2.13 on 2026-04-11 16:15

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.db import migrations, models


def backfill_product_categories(apps, schema_editor):
    Category = apps.get_model('inventory', 'Category')
    Product = apps.get_model('inventory', 'Product')

    uncategorized, _ = Category.objects.get_or_create(
        name='Uncategorized',
        defaults={'is_active': True},
    )

    for product in Product.objects.all().iterator():
        category_name = (product.category or '').strip() or 'Uncategorized'
        category, _ = Category.objects.get_or_create(
            name=category_name,
            defaults={'is_active': True},
        )
        if product.category_ref_id != category.id:
            product.category_ref_id = category.id
            product.save(update_fields=['category_ref'])
        if not product.category:
            product.category = uncategorized.name if category_name == 'Uncategorized' else category.name
            product.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_discount_type_product_discount_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(default=inventory.models.get_default_category_pk, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category'),
        ),
        migrations.RunPython(backfill_product_categories, migrations.RunPython.noop),
    ]
