# Generated by Django 5.2.13 on 2026-04-12 05:33

import django.db.models.deletion
import django.utils.timezone
import inventory.models
from django.conf import settings
from django.db import migrations, models
from uuid import uuid4


def _build_unique_code(prefix, used_codes, fallback_id):
    code = f"{prefix}-{fallback_id:06d}"
    if code not in used_codes:
        used_codes.add(code)
        return code
    while True:
        code = f"{prefix}-{uuid4().hex[:8].upper()}"
        if code not in used_codes:
            used_codes.add(code)
            return code


def backfill_inventory_codes(apps, schema_editor):
    Category = apps.get_model("inventory", "Category")
    Location = apps.get_model("inventory", "Location")
    Product = apps.get_model("inventory", "Product")
    ProductVariant = apps.get_model("inventory", "ProductVariant")

    category_map = {item.id: item for item in Category.objects.all()}
    used_category_codes = {
        (item.code or "").strip().upper()
        for item in category_map.values()
        if (item.code or "").strip()
    }

    resolved = {}

    def resolve_category(cat):
        if cat.id in resolved:
            return resolved[cat.id]

        code = (cat.code or "").strip().upper()
        if not code:
            if (cat.name or "").strip().lower() == "uncategorized" and "UNCATEGORIZED" not in used_category_codes:
                code = "UNCATEGORIZED"
                used_category_codes.add(code)
            else:
                code = _build_unique_code("CAT", used_category_codes, cat.id)
        if cat.parent_id and cat.parent_id in category_map:
            parent_level, parent_path = resolve_category(category_map[cat.parent_id])
            level = parent_level + 1
            path = f"{parent_path}/{code}"
        else:
            level = 0
            path = code

        cat.code = code
        cat.level = level
        cat.path = path
        resolved[cat.id] = (level, path)
        return resolved[cat.id]

    for category in category_map.values():
        resolve_category(category)
        category.save(update_fields=["code", "level", "path"])

    used_location_codes = {
        (item.code or "").strip().upper()
        for item in Location.objects.all()
        if (item.code or "").strip()
    }
    for location in Location.objects.all():
        code = (location.code or "").strip().upper()
        if not code:
            code = _build_unique_code("LOC", used_location_codes, location.id)
            location.code = code
            location.save(update_fields=["code"])

    used_product_codes = {
        (item.code or "").strip().upper()
        for item in Product.objects.all()
        if (item.code or "").strip()
    }
    for product in Product.objects.all():
        code = (product.code or "").strip().upper()
        if not code:
            code = _build_unique_code("PRD", used_product_codes, product.id)
            product.code = code
            product.save(update_fields=["code"])

    used_barcodes = {
        (item.barcode or "").strip().upper()
        for item in ProductVariant.objects.all()
        if (item.barcode or "").strip()
    }
    for variant in ProductVariant.objects.all():
        barcode = (variant.barcode or "").strip().upper()
        if barcode:
            continue
        while True:
            barcode = uuid4().hex.upper()
            if barcode not in used_barcodes:
                used_barcodes.add(barcode)
                break
        variant.barcode = barcode
        variant.save(update_fields=["barcode"])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_category_product_category_ref'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('normalized_name', models.CharField(db_index=True, max_length=250)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('movement_type', models.CharField(choices=[('IN', 'IN'), ('OUT', 'OUT'), ('TRANSFER', 'TRANSFER'), ('ADJUSTMENT', 'ADJUSTMENT')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('reference_type', models.CharField(blank=True, default='', max_length=80)),
                ('reference_id', models.CharField(blank=True, default='', max_length=120)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='category',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('store', 'Store'), ('warehouse', 'Warehouse'), ('outlet', 'Outlet')], default='store', max_length=20),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_locations', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='is_perishable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_serialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='batch_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stockentry',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(blank=True, default=inventory.models.get_default_barcode, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_inventory_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(default=inventory.models.get_default_category_code, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='code',
            field=models.CharField(default=inventory.models.get_default_location_code, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default=inventory.models.get_default_product_code, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='barcode',
            field=models.CharField(default=inventory.models.get_default_barcode, max_length=32, unique=True),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price__gte', 0)), name='product_variant_cost_price_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('reserved_quantity__gte', 0)), name='stock_reserved_quantity_gte_zero'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', models.F('reserved_quantity'))), name='stock_reserved_quantity_lte_quantity'),
        ),
        migrations.AddConstraint(
            model_name='stockentry',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gte', 0)), name='stock_entry_unit_cost_gte_zero'),
        ),
        migrations.AddField(
            model_name='categorycorrection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_corrections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categorycorrection',
            name='predicted_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prediction_corrections', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='categorycorrection',
            name='selected_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_corrections', to='inventory.category'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.productvariant'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['variant', 'location'], name='inventory_s_variant_fcb2f1_idx'),
        ),
    ]
