# Generated by Django 5.2.13 on 2026-04-17 05:14

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
