# Generated by Django 6.0.3 on 2026-04-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=20,
                choices=[
                    ('cash', 'Cash on Delivery'),
                    ('upi', 'UPI'),
                    ('card', 'Card'),
                    ('netbanking', 'Net Banking'),
                    ('wallet', 'Wallet'),
                ],
            ),
        ),
    ]
