# Generated by Django 5.2.13 on 2026-04-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0013_productvariant_image"),
        ("orders", "0003_order_order_total_amount_gte_zero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.SET_NULL,
                related_name="order_items",
                to="inventory.productvariant",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="orderitem",
            name="unique_order_item_product_per_order",
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.UniqueConstraint(
                fields=("order", "product", "variant"),
                name="unique_order_item_product_variant_per_order",
            ),
        ),
    ]
