# Generated by Django 6.0.3 on 2026-04-04 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_6d43f1_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type'], name='notificatio_alert_t_c9557f_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['location', 'created_at'], name='notificatio_locatio_d82a6f_idx'),
        ),
    ]
