# Generated by Django 5.2.13 on 2026-04-21 04:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_productvariant_image'),
        ('notifications', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='event_key',
            field=models.CharField(blank=True, db_index=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('stock_update', 'Stock Update'), ('zero_stock', 'Zero Stock'), ('expiry', 'Expiry'), ('flagged', 'Flagged'), ('payment', 'Payment')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['user', 'alert_type', 'event_key'], name='notificatio_user_id_e2e66c_idx'),
        ),
    ]
